# Generated by Django 5.0.1 on 2024-01-27 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favouritestock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritestock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
